version: "3.9"
services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: research_project_development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin_config/servers.json:/pgadmin4/servers.json
    depends_on:
      - db
    networks:
      - my-network

  web:
    build: .
    container_name: research_project-web
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: research_project_development
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
    volumes:
      - .:/rails:cached
      - bundle_cache:/usr/local/bundle 
    networks:
      - my-network

volumes:
  postgres_data:
  pgadmin_data:
  bundle_cache:

networks:
  my-network:
    driver: bridge
